/*
Task 4 Database: world

Simple Method:
  - Average the life expectancy of all countries where the language is spoken.

more correct way to compute average life expectancies per languages:

Weighted Method:
  - Estimate the number of speakers of each language in each country as:
       country.Population * countrylanguage.Percentage / 100
    then calculate a weighted average of country LifeExpectancy values, weighted by
    the estimated number of speakers.

Why the second strategy is better:
The simple average gives a tiny country and a very large country the same weight.
The weighted method gives more influence to countries where more people speak the
language.
*/

-- Query 1: Simple Method
SELECT
    cl.Language,
    AVG(c.LifeExpectancy) AS SimpleAverageLifeExpectancy,
    COUNT(*) AS NumberOfCountries
FROM countrylanguage AS cl
JOIN country AS c
    ON c.Code = cl.CountryCode
WHERE c.LifeExpectancy IS NOT NULL
  AND cl.Percentage > 0
GROUP BY cl.Language
ORDER BY SimpleAverageLifeExpectancy DESC, cl.Language;


-- Query 2: Weighted Method
WITH language_speakers AS (
    SELECT
        cl.Language,
        c.Name AS CountryName,
        c.LifeExpectancy,
        c.Population,
        cl.Percentage,
        c.Population * cl.Percentage / 100.0 AS EstimatedSpeakers
    FROM countrylanguage AS cl
    JOIN country AS c
        ON c.Code = cl.CountryCode
    WHERE c.LifeExpectancy IS NOT NULL
      AND c.Population > 0
      AND cl.Percentage > 0
)
SELECT
    Language,
    SUM(LifeExpectancy * EstimatedSpeakers) / SUM(EstimatedSpeakers) AS WeightedAverageLifeExpectancy,
    SUM(EstimatedSpeakers) AS EstimatedTotalSpeakers,
    COUNT(*) AS NumberOfCountries
FROM language_speakers
GROUP BY Language
ORDER BY WeightedAverageLifeExpectancy DESC, Language;



-- ============================================================
-- Optional comparison: simple vs weighted result side by side, generated by LLM
-- ============================================================

WITH simple_average AS (
    SELECT
        cl.Language,
        AVG(c.LifeExpectancy) AS SimpleAverageLifeExpectancy
    FROM countrylanguage AS cl
    JOIN country AS c
        ON c.Code = cl.CountryCode
    WHERE c.LifeExpectancy IS NOT NULL
      AND cl.Percentage > 0
    GROUP BY cl.Language
),
weighted_average AS (
    SELECT
        cl.Language,
        SUM(c.LifeExpectancy * (c.Population * cl.Percentage / 100.0))
            / SUM(c.Population * cl.Percentage / 100.0) AS WeightedAverageLifeExpectancy
    FROM countrylanguage AS cl
    JOIN country AS c
        ON c.Code = cl.CountryCode
    WHERE c.LifeExpectancy IS NOT NULL
      AND c.Population > 0
      AND cl.Percentage > 0
    GROUP BY cl.Language
)
SELECT
    s.Language,
    s.SimpleAverageLifeExpectancy,
    w.WeightedAverageLifeExpectancy,
    w.WeightedAverageLifeExpectancy - s.SimpleAverageLifeExpectancy AS Difference
FROM simple_average AS s
JOIN weighted_average AS w
    ON w.Language = s.Language
ORDER BY ABS(Difference) DESC, s.Language;
